### ISSUE TITLE
Community tasks 新手任务计划

### ISSUE THREAD

**Issue by EvenLjj** [sofastack/sofa-rpc#1127]
# Community tasks
As a programming enthusiast , have you ever felt that you want to participate in the development of an open source project, but don't know where to start?
In order to help everyone better participate in open source projects, theSOFASTCK community will regularly publish community tasks to help everyone learn by doing!

# Task List
Tasks of different difficulty are released:
### SDK related

- [ ] Provide some enums for bindings #1031

### Document related

- [ ] Improve the documentation of configuration parameters #1030 
- [ ] Improve the documentation of using Nacos as the registration center [doc](https://www.sofastack.tech/projects/sofa-rpc/registry-nacos/)
- [ ] Improve the documentation of using Zookeeper as the registration center [doc](https://www.sofastack.tech/projects/sofa-rpc/registry-zookeeper/)

### SDK related

- [ ] SofaService annotation support Component #1031  

### Feature
- [ ] Improve asynchronous functionality through CompletableFuture #945 

### Feature

- [ ] JFR buried point

**Comment by seeflood** [comment]
chinese:
# 新手任务计划
作为技术同学，你是否有过“想参与某个开源项目的开发、但是不知道从何下手”的感觉？
为了帮助大家更好的参与开源项目，MOSN社区会定期发布适合新手的新手开发任务，帮助大家learning by doing!

# 任务列表
任务分为不同难度：
## Easy——从这里开始，成为Contributor!
- [ ] 在服务引用和发布时，使用枚举值替代字符串硬编码。 见https://github.com/sofastack/sofa-rpc/issues/1031
![image](https://user-images.githubusercontent.com/26001097/141305613-4522f07e-ad4f-44fa-9061-ea38a0756c3f.png)

- [ ] 优化集成nacos的文档 https://www.sofastack.tech/projects/sofa-rpc/registry-nacos/
- [ ] 优化集成zk注册中心的文档  https://www.sofastack.tech/projects/sofa-rpc/registry-zookeeper/
- [ ] 优化配置文档 https://github.com/sofastack/sofa-rpc/issues/1030
 
## Medium
- [ ] 让用户使用@SofaService后不需要再写@Component 见https://github.com/sofastack/sofa-rpc/issues/1031
![](https://user-images.githubusercontent.com/26001097/141304508-ca836026-3d4d-4173-b25d-10b9bc53a5ef.png)

- [ ] 优化sofarpc的异步编程体验
#945 

## Hard
- [ ] JFR埋点

**Comment by seeflood** [comment]
chinese:
# 新手任务计划
作为技术同学，你是否有过“想参与某个开源项目的开发、但是不知道从何下手”的感觉？
为了帮助大家更好的参与开源项目，SOFAStack & MOSN社区会定期发布适合新手的新手开发任务，帮助大家learning by doing!

# 任务列表
任务分为不同难度：
## Easy——从这里开始，成为Contributor!
- [ ] 在服务引用和发布时，使用枚举值替代字符串硬编码。 见https://github.com/sofastack/sofa-rpc/issues/1031
![image](https://user-images.githubusercontent.com/26001097/141305613-4522f07e-ad4f-44fa-9061-ea38a0756c3f.png)

- [ ] 优化集成nacos的文档 https://www.sofastack.tech/projects/sofa-rpc/registry-nacos/
- [ ] 优化集成zk注册中心的文档  https://www.sofastack.tech/projects/sofa-rpc/registry-zookeeper/
- [ ] 优化配置文档 https://github.com/sofastack/sofa-rpc/issues/1030
 
## Medium
- [ ] 让用户使用@SofaService后不需要再写@Component 见https://github.com/sofastack/sofa-rpc/issues/1031
![](https://user-images.githubusercontent.com/26001097/141304508-ca836026-3d4d-4173-b25d-10b9bc53a5ef.png)

- [ ] 优化sofarpc的异步编程体验
#945 

## Hard
- [ ] JFR埋点

**Comment by seeflood** [comment]
Hi @EvenLjj ,please:
- add more description for `JFR buried point`
- add more description for which part of the nacos and zk documents are not good and how to improve them

**Comment by IrvingOS** [comment]
Provide some enums for service binding instead of hard code with string#1031 
Please assign to me

**Comment by EvenLjj** [comment]
> Provide some enums for service binding instead of hard code with string#1031 Please assign to me

Hi @IrvingOS, welcome, this change involves a change in the annotation API, the code repository is in the[ sofaboot project](https://github.com/sofastack/sofa-boot).

**Comment by seeflood** [comment]
@IrvingOS Cool , this task will be assigned to you, see https://github.com/sofastack/sofa-rpc/issues/1031#issuecomment-966291369
To solve this issue,the code should commit to https://github.com/sofastack/sofa-boot
If you met any problem or have any questions, feel free to reach out for help

**Comment by ZLBer** [comment]
@EvenLjj @seeflood   hi, i want to  add a new registry  component `polaris` , the project website : https://github.com/polarismesh/polaris , https://polarismesh.cn/#/ .  can  i try to do this ？

**Comment by seeflood** [comment]
@EvenLjj hi, could u please help check this proposal

> @EvenLjj @seeflood hi, i want to add a new registry component `polaris` , the project website : https://github.com/polarismesh/polaris , https://polarismesh.cn/#/ . can i try to do this ？

**Comment by EvenLjj** [comment]
> @EvenLjj @seeflood hi, i want to add a new registry component `polaris` , the project website : https://github.com/polarismesh/polaris , https://polarismesh.cn/#/ . can i try to do this ？

@ZLBer Of course yes, you can add related registry plugins based on the extension point mechanism. It is best to create an issue description, and we can discuss in the issue in the future. Very welcome to join.

**Comment by ZLBer** [comment]
@EvenLjj  well, i create a issue

**Comment by imherewait** [comment]
After the @SofaService is annotated, the @Component should not be necessary #1031
Please assign to me thanks

**Comment by MingJunDuan** [comment]
> After the @SofaService is annotated, the @component should not be necessary #1031 Please assign to me thanks

Hi, how do you solve the problem?

**Comment by KevinClair** [comment]
Hello, is there any community tasks left?

**Comment by imherewait** [comment]
> > After the @SofaService is annotated, the @component should not be necessary #1031 Please assign to me thanks
> 
> Hi, how do you solve the problem?

相应issue有评论哈，可以看一下

**Comment by krisjin** [comment]
@EvenLjj   hi,  i want to do this 优化sofarpc的异步编程体验 https://github.com/sofastack/sofa-rpc/issues/945

**Comment by EvenLjj** [comment]
> @EvenLjj hi, i want to do this 优化sofarpc的异步编程体验 #945

Welcome, looking forward to your PR.

**Comment by sususama** [comment]
@EvenLjj Hi,现在还有什么可以入门做的东西吗？
